# This is a basic workflow to help you get started with Actions

name: BuildDocs

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
   push:
    paths:
      - 'docs/**.md'
  
permissions: write-all

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
     
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - name: Install dependencies
        run: npm ci --ignore-scripts

      # Runs a single command using the runners shell
      #- name: Run a one-line script
      #  run: ../../deploy.sh

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        
        run: |
          echo Setting up NPM
          npm ci
          echo Building docs
          cd /home/runner/work/VecMath/VecMath
          pwd
          chmod u+x ./deploy.sh
          ./deploy.sh
          git push -f git@github.com:samynk/VecMath.git main:gh-pages

